spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8888

log:
  app-name: twitter-to-kafka-service

twitter-to-kafka-service:
  enable-mock-tweets: true
