spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: "optional:configserver:twitter-to-kafka-service"

  cloud:
    config:
      name: twitter-to-kafka-service,config-client
      uri: http://localhost:8888
      enabled: false